import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { Inter } from 'next/font/google'
import { cn } from '@/lib/utils'
import { SidebarProvider, SidebarInset } from '@/components/ui/sidebar'
import { TooltipProvider } from '@/components/ui/tooltip'
import { AppSidebar } from '@/components/workspace/shell/app-sidebar'
import { CollapsedSidebarTrigger } from '@/components/workspace/shell/collapsed-sidebar-trigger'
import { getSession } from '@/auth'
import { prisma } from 'db'
import type { SessionSummary } from '@/lib/api'

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getSession().catch(() => null)
  const userId = session?.userId
  const user = userId
    ? await prisma.user
        .findUnique({
          where: { id: userId },
          select: { name: true, email: true, avatarUrl: true },
        })
        .catch(() => null)
    : null
  const recentSessions: SessionSummary[] = userId
    ? (
        await prisma.session
          .findMany({
            where: { userId },
            orderBy: { createdAt: 'desc' },
            take: 10,
            select: {
              id: true,
              prompt: true,
              createdAt: true,
              status: true,
              repo: { select: { fullName: true } },
            },
          })
          .catch(() => [])
      ).map((s) => ({
        id: s.id,
        prompt: s.prompt,
        createdAt: s.createdAt.toISOString(),
        status: s.status,
        repoFullName: s.repo?.fullName,
      }))
    : []

  return (
    <html lang="en" suppressHydrationWarning className={cn('dark font-sans', inter.variable)}>
      <body
        suppressHydrationWarning
        className={`${geistMono.variable} bg-background text-foreground`}
      >
        <TooltipProvider>
          {session?.user && userId ? (
            <SidebarProvider defaultOpen={true}>
              <AppSidebar user={user} recentSessions={recentSessions} />
              <SidebarInset>
                <CollapsedSidebarTrigger />
                <div className="relative flex h-full min-h-0 flex-1 flex-col">{children}</div>
              </SidebarInset>
            </SidebarProvider>
          ) : (
            <div className="flex min-h-svh flex-col">{children}</div>
          )}
        </TooltipProvider>
      </body>
    </html>
  )
}
