export const OPENROUTER_BASE_URL = 'https://openrouter.ai/api/v1'
export const OPENROUTER_DEFAULT_MODEL = 'openai/gpt-4o-mini'
export const OPENCODE_GO_BASE_URL = 'https://opencode.ai/zen/go/v1'
export const OPENCODE_GO_DEFAULT_MODEL = 'mimo-v2.5'
export const MAX_TOOL_OUTPUT_CHARS = 10_000
export const TOOL_OUTPUT_SPILL_CHARS = 20_000
export const TOOL_OUTPUT_PREVIEW_CHARS = 8000
export const READ_DEFAULT_MAX_LINES = 2000
export const READ_DEFAULT_MAX_BYTES = 64 * 1024
export const STEERING_MESSAGE_CHARS = 8000
export const MAX_COMMAND_TIMEOUT_MS = 10 * 60 * 1000
export const DEFAULT_CONTEXT_WINDOW = 128_000
export const DEFAULT_OPENAI_TIMEOUT_MS = 60_000
export const DEFAULT_OPENAI_MAX_RETRIES = 3
